on:
  workflow_dispatch:
  schedule:
    - cron: '50 5 * * *'

jobs:
  update-example-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::quantmod
            any::dplyr
            any::ggplot2
            any::ggthemes
            any::lubridate
            any::MASS
            any::gridExtra
            any::scales
            any::yaml

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Update YAML key value
        run: |
          yq '.output_file_path = "example-chart"' config.yml > updated_yaml.yml
          mv updated_yaml.yml config.yml

      - name: Print file contents
        run: |
          cat config.yml

      - name: Create chart
        run: Rscript -e 'source("RValuationAnalysis.R")'

      - name: Update YAML key value
        run: |
          yq '.output_file_path = "example-chart-inflation-adjusted"' config.yml > updated_yaml.yml
          mv updated_yaml.yml config.yml

      - name: Update YAML key value
        run: |
          yq '.without_inflation = "TRUE"' config.yml > updated_yaml.yml
          mv updated_yaml.yml config.yml

      - name: Print file contents
        run: |
          cat config.yml

      - name: Create chart
        run: Rscript -e 'source("RValuationAnalysis.R")'

      - name: Commit chart
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add example-chart.png
          git add example-chart-inflation-adjusted.png
          git commit -m 'NASDAQ 100 charts updated' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
