on:
  workflow_dispatch:
  schedule:
    - cron: '50 5 * * *'

jobs:
  update-example-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::quantmod
            any::dplyr
            any::ggplot2
            any::ggthemes
            any::lubridate
            any::MASS
            any::gridExtra
            any::scales
            any::yaml

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Update values.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'config.yml'
          propertyPath: 'output_file_path'
          value: example-chart
          commitChange: false

      - name: Create chart
        run: Rscript -e 'source("RValuationAnalysis.R")'

      - name: Update values.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'config.yml'
          propertyPath: 'output_file_path'
          value: example-chart-inflation-adjusted
          commitChange: false

      - name: Update values.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'config.yml'
          propertyPath: 'without_inflation'
          value: 'True'
          commitChange: false

      - name: Print file contents
        run: |
          cat config.yml

      - name: Create chart
        run: Rscript -e 'source("RValuationAnalysis.R")'

      - name: Commit chart
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add example-chart.png
          git add example-chart-inflation-adjusted.png
          git commit -m 'NASDAQ 100 charts updated' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
